### ISSUE TITLE
Title isn't being saved

### ISSUE THREAD

**Issue by xhuytox** [Alaanor/beatlist#1]
It doesn't look like the playlist Title field is being saved. 

![image](https://user-images.githubusercontent.com/20061642/60412716-195e2000-9b87-11e9-8e4a-ba88bd56d436.png)

**Comment by Alaanor** [comment]
Fixed with ea49b28. Meanwhile this fix take place in the next release, you can always go edit the json file yourself, it's pretty simple. There's a field called `playlistTitle`, it's should be the first one.

Thanks for reporting it 👍

**Comment by Alaanor** [comment]
Actually that was dumb to not release something, so I released [v1.0.1](https://github.com/Alaanor/beatlist/releases/tag/v1.0.1) 👌
