### ISSUE TITLE
Tried to load songs; this ended up cutting around 100 out of beatlist

### ISSUE THREAD

**Issue by Yonokid** [Alaanor/beatlist#12]
![failed](https://user-images.githubusercontent.com/37304577/69199724-dafdd900-0b06-11ea-8877-85f800dc9003.PNG)

I'm not entirely sure what the error is, but I think it may have to do with the legacy song format. The songs that didn't load were some of the first I got.

**Comment by Alaanor** [comment]
After a little discussion on the discord server/dm, we finally found the bug and I sent a commit that fixed it: 9b144d0773b51601edae565650840a436eccf5c4. I'm closing the issue as it is solved.
