### ISSUE TITLE
One-click install isn't a one-click install

### ISSUE THREAD

**Issue by VeikkoLehmuskorpi** [Alaanor/beatlist#14]
Unlike with ModAssistant, clicking a "one-click install" button on such site as bsaber.com opens the song page in BeatList instead of quietly installing it. 

So until this behaviour is changed, how could I make BeatList ignore the "beatsaver://" links?

**Comment by Alaanor** [comment]
Hello,

For the first point you're right. It should be a real click install, multiple user already suggested me to change. So this point is already on the roadmap and will be fixed on the next major release.

For the second point, you're also right, and damn, I haven't though about this, my app is actually overriding the preference each time you start it 😟 . One temporary solution is to start mod assistant and quickly toggle again the one click install in their options to trigger the event that register them as the one click handler, so beatlist won't open it. Unfortunately with the current code, each time beatlist start it will register as the beatsaver:// handler again.

I will find a solution for this point on the next release - added on the roadmap. I will add an option to enable/disable the one-click install so you guys have control on it.

I'm currently doing a quite huge change on beatlist so the next release will takes time, if you really wish to use beatlist meanwhile you can always compile yours while commenting this line (or dm me on discord, I will build one for you):
https://github.com/Alaanor/beatlist/blob/ce60d0e65589618111bbe301bfa40e00477d83a3/src/background.ts#L107

**Comment by VeikkoLehmuskorpi** [comment]
Thanks, the new build works for me as I can now let ModAssistant handle the installs.

> For the first point you're right. It should be a real click install, multiple user already suggested me to change. So this point is already on the roadmap and will be fixed on the next major release.

Is the roadmap publicly available? I thought this might have been requested already but didn't see an mention of it or an issue so I opened one.

**Comment by Alaanor** [comment]
It is !

- Main task:  https://www.notion.so/alaanor/d0d2650fc6994825a9d099529dc0d9ab?v=f82852f83861400ea341bdb4c2ac7746 (What I see of beatlist on the long term)
- Detail task: https://www.notion.so/alaanor/389d3ae317524e90a8fe12e6feb82320?v=80c6eec5e3b14a9199618e42ed1c01d6 (What I'm currently working on, on a closer detail for the next release)

It is on the welcome message on my discord server. I'm probably going to put that on the readme on the next release as well :)

**Comment by Alaanor** [comment]
Should now be solved with the release of 1.2.0. I'm closing the issue.
