### ISSUE TITLE
Set default items per page?

### ISSUE THREAD

**Issue by katherinehackworth** [Alaanor/beatlist#15]
Seems like an easy enhancement, but much needed. Just allow setting the items per page in settings so it doesn't default to 12 on each run of the app!

**Comment by Alaanor** [comment]
Oh strange, I was pretty sure I did something for this 😄 

Added it the roadmap ~ I'll add that for the next release 👌

**Comment by Alaanor** [comment]
Implemented in 1.2.0, it now store that preferences 😄 . Closing this issue.
