### ISSUE TITLE
One click download all songs from playlist

### ISSUE THREAD

**Issue by asc11cat** [Alaanor/beatlist#17]
^ would be really nice, and probably easy to implement

**Comment by Alaanor** [comment]
Yes, I will and it is planned since a long time ago. I'm just doing a rewrite so it will take time until the next major version. You can check the rewrite branch or the discord for progresses.

**Comment by Alaanor** [comment]
![image](https://user-images.githubusercontent.com/8039130/79778969-dea5be00-8339-11ea-8164-4879f9126cf3.png)
![image](https://user-images.githubusercontent.com/8039130/79778975-e1081800-8339-11ea-9f0c-e631f6994a76.png)

**Comment by livejamie** [comment]
How can I install this version?

**Comment by Alaanor** [comment]
It's on the develop branch. The reason there's no release yet with all these new thing is bcz the update was a complete rewrite and hence there's still some functionality to implement compared to the previous version. (Atm only one click feature and beastsaver playlist page are missing) if you really want it faster I think it would be stable enough to use it without these feature. Just DM on discord, I'll make a custom build for you (you can also build yourself if you know the tools)
