### ISSUE TITLE
Severe memory leak?

### ISSUE THREAD

**Issue by katherinehackworth** [Alaanor/beatlist#18]
I believe beatlist was running in the background, because I got an out of memory error. When I checked what was going on, I had a pagefile of 34 GB on my C:\ drive, and my 16 GB of ram was entirely being consumed by beatlist. Does the app have any logs that I can include?

**Comment by Alaanor** [comment]
😨 No, I haven't any logs files generated, not as far as I know. I don't know what to do there. But, there is something I can't understand, you're saying that Beatlist was running in background, does that mean you had the app opened for hours ? Or did this happen after you completely closed the app. If you closed it, Beatlist should normally have all his processes down.

**Comment by katherinehackworth** [comment]
I had closed the app, but for some reason some background process kept running. I only noticed when I went to task manager and beatlist.exe was eating all my ram. There wasn't a window open though so I think it's a process it failed to kill off.

**Comment by katherinehackworth** [comment]
I can try and replicate it again but I mean there's not a whole lot that'd help with since there's no logs :/

**Comment by Alaanor** [comment]
If I could reproduce the situation I can debug it and solve. The difference we have is that yours seems to not completely close if you close. A clean installation of beatlist should have all his process down if you close it. If I have time I'll read some things about how I can implement some log trace and make them actually useful, how developers implement them.

As I have a complete rewrite of beatlist ongoing, I'd suggest that we wait for the oncoming 1.2. All code is changed and so are the bugs. If this happens again in the next version, I'll hunt down the memory leak.

**Comment by Alaanor** [comment]
> As I have a complete rewrite of beatlist ongoing, I'd suggest that we wait for the oncoming 1.2. All code is changed and so are the bugs. If this happens again in the next version, I'll hunt down the memory leak.

1.2.0 is now released, so I'm closing this issue in hope this fixed it. But if you still have this problem, don't hesitate to re-open the issue.
