### ISSUE TITLE
Playlist loading breaks when a non-playlist file is in the user's Playlist folder

### ISSUE THREAD

**Issue by legoandmars** [Alaanor/beatlist#19]
Tested with both an .exe file and a .jpg file in the `Beat Saber/Playlists` folder

When a non-playlist file is present, you cannot properly add new playlists or create a new one from beatlist. Playlists added to the `Playlists` folder after the non-playlist file is added will not appear in beatlist's Playlist tab

If beatlist is installed AFTER a non-playlist file is already present, no playlists will properly load in beatlist until the non-playlist file is removed.

**Comment by Alaanor** [comment]
Yeah I saw this a moment ago, the rewrite branch already contain a fix for this 👌. Just need to wait for that never releasing 1.2 😄 (I just need time lol)

**Comment by Alaanor** [comment]
As 1.2 got release I'm now closing this issue. It should be fixed.
