### ISSUE TITLE
OneClick does not work when beatlist is already showing a map opened with OneClick 

### ISSUE THREAD

**Issue by Gordin** [Alaanor/beatlist#21]
When you use OneClick and beatlist opens the detail page of a map, clicking OneClick on another map will bring beatlist to the front but it won't actually open the page of the map because another map is already open.

**Comment by Alaanor** [comment]
This is a valid issue and it will be fixed on the next version. 👌

**Comment by Alaanor** [comment]
This issue has been fixed in 1.2 which just got released 😄 I'm closing this issue
