### ISSUE TITLE
Starting a new search does not reset the page

### ISSUE THREAD

**Issue by wolrah** [Alaanor/beatlist#23]
If I am browsing the latest songs and I'm a few dozen pages deep, then I go to search for something, Beatlist stays set to whatever page number I was on.  If there aren't that many pages of search results it looks like there are no results until I manually page back to a lower number.

I think it would be a much better user experience for it to reset back to page 1 when running a new search.

**Comment by Alaanor** [comment]
Ok I wasn't sure if I had it fixed on my rewrite branch. It is not. I'll be sure to change this 😃
