### ISSUE TITLE
Timing out and freezing

### ISSUE THREAD

**Issue by fuyushi** [Alaanor/beatlist#28]
Whenever I try to download a song or even just scan my library the program seems to get stuck at some point and never finish, until the window turns solid white. 
For downloading a song the moving circles progress bar will continously spin forever without finishing (the song seems to have downloaded though in beat saber folder). 
For scanning library, it gets stuck at the last song until the program turns solid white. (Scanning Song 4892/4893 in my case)

**Comment by Alaanor** [comment]
Yeah, seems like a bug. Doesn't even surprise me with the amount of song you got 😄. Would you mind reaching me on discord ? Alaanor#9999. We could try to find a solution and see what can be done.

**Comment by Alaanor** [comment]
I tried with a few people to handle big scan with 1.2.0. It worked just fine. I'm closing this issue, but if you still have problem, please re-open the issue and tell it. I will try my best to help.
