### ISSUE TITLE
Beatlist takes precedence over ModAssistant in opening one-click install links

### ISSUE THREAD

**Issue by milovincent** [Alaanor/beatlist#30]
Having an option as simple as a checkbox for turning this off would be great, especially for scripts that open beatsaver:// urls in order to download songs based on certain criteria.

**Comment by Alaanor** [comment]
Related to #14, this is a known bug and I will fix it. I know I'm slow with release but late or not, it will happens one day :D. I know some user downloaded an older version where I haven't implemented it yet. A temporary solution is given in the #14 too.

**Comment by Alaanor** [comment]
This is fixed in 1.2.0 which just go released. Closing the issue. You now have choice to let either beatlist or mod assistant.

![image](https://user-images.githubusercontent.com/8039130/82228088-f49ea280-9928-11ea-9db6-551163e768f2.png)
