### ISSUE TITLE
Please add batch selection

### ISSUE THREAD

**Issue by loyle5** [Alaanor/beatlist#31]
Please add batch selection
too many Local songs it's hard to add to playlist once

**Comment by Alaanor** [comment]
![image](https://user-images.githubusercontent.com/8039130/79127188-b817de00-7da1-11ea-825d-0c9e3b691d6e.png)

It's a feature I've been working on already. Here's what it looks like atm. So you'll get it for the next version :)

**Comment by Alaanor** [comment]
released 1.2, this feature is now available :) Closing the issue.
