### ISSUE TITLE
Online Playlists Broken?

### ISSUE THREAD

**Issue by livejamie** [Alaanor/beatlist#38]
Getting "Couldn't load playlists" when going to Online Playlists

![image](https://user-images.githubusercontent.com/49513/81227772-ce304d00-8fa1-11ea-9bda-f8aaf51416ca.png)

**Comment by Alaanor** [comment]
I just reinstalled 1.1.4 to check this. Seems like it works on my end. It's probably a network issue temporarily or the bsaber server were down yesterday for a little moment maybe. That's what this message meant, he couldn't reach the server for some reason.

Can you confirm it works now ?

**Comment by Alaanor** [comment]
Got reported in dm through discord that it works now. Closing the issue.
