### ISSUE TITLE
Show playlist under the Beat Local

### ISSUE THREAD

**Issue by Rawk3rs** [Alaanor/beatlist#40]
Hi there,

It would be really handy to be able to see under the Beat Local list the playlists a song is in using the playlist thumbnails I guess like the way you did for the difficulties. 

That way, it would be quite easy to spot songs that are not in a playlist yet

**Comment by Alaanor** [comment]
Hello, yes, it is planned. 😄

**Comment by danagin** [comment]
I would love to see this as well! Thanks for this awesome utility!
