### ISSUE TITLE
Have the "preview beatmap" button visible in the "Actions" column

### ISSUE THREAD

**Issue by TLNBS2405** [Alaanor/beatlist#42]
Hello,

When I search for a map and I see a list of map there, it would be nice to have the preview button in the results instead of clicking on each of them -> then preview -> go back -> try an another one

**Comment by Alaanor** [comment]
Mhhh this will start to have a lot of button. Maybe I should think about a expandable menu there will all action available.

Doable I think, I'll probably implement that.
