### ISSUE TITLE
Sort songs by title?

### ISSUE THREAD

**Issue by pmcthor777** [Alaanor/beatlist#52]
First I'd like to thank you for creating this awesome app. Makes creating and managing playlists a breeze. I do wish there's a sort by song title feature. Is it possible to add this feature?

Thanks

**Comment by Alaanor** [comment]
Locally there is, but on the online one, I can't unfortunately. This is out of my control.
![image](https://user-images.githubusercontent.com/8039130/85116718-091ed500-b21e-11ea-9dba-8a6354cc31d4.png)

if you meant something else or have something to add, don't hesitate to tell it :)

**Comment by pmcthor777** [comment]
Ah sorry, I was using an older version. Thank you.
