### ISSUE TITLE
Cannot download any songs

### ISSUE THREAD

**Issue by flyx** [Alaanor/beatlist#73]
Whenever I try to download a song, I get a red popup with the following error message:

> Couldn't download beatmap. [Error]: ESOCKETTIMEDOUT

Generally the internet connection works fine as I can search for songs, just the download fails.

**Comment by SWinxy** [comment]
Beatsaver is currently down. Uptime has been quite shaky these past couple of weeks, sadly.

**Comment by flyx** [comment]
Ah okay, bad timing to test this app then.

Wondering why I do get a song listing though. Is that hosted elsewhere?

**Comment by SWinxy** [comment]
Not sure. I haven't looked too deeply into the code but from what I can tell is that it saves the last known top maps? @Alaanor might not even know either lol.

**Comment by Alaanor** [comment]
Nope. It does indeed fetch on beatsaver. But beatsaver seems to have separated server for the front and the api. From what I can observe, the current situation is:
 - The api is up
 - The website is down
 - The cdn is down (where the actual download is)
