### ISSUE TITLE
Play song inside the app

### ISSUE THREAD

**Issue by pravic** [Alaanor/beatlist#8]
Is it possible?

**Comment by Alaanor** [comment]
Hello, I'm considering adding this possibility for one of the next versions 👍 

So not for today, unfortunately, but it is in my roadmap.

**Comment by asc11cat** [comment]
Song preview would be really nice, so users can finally move from beatdrop which is crashing every second.

**Comment by Alaanor** [comment]
I wrote a simple audio preview on the rewrite branch. It will be on the upcoming beatlist 1.2.

There's some limitation though; I checked how beatsaver does his preview, they simply download the entire map. There's no alternate way. So at the moment I just made this button available when the map is downloaded.

If you feel the need that beatlist temporary download the entire beatmap, don't install it and preview the song, then request it.
