### ISSUE TITLE
Removing Playlist thumbnail when adding songs

### ISSUE THREAD

**Issue by Rawk3rs** [Alaanor/beatlist#80]
My Playlists are showing properly in app and in game, however, as soon as I add a new song to any playlist, the concerned thumbnail disapperas in app and in game. I then have to add it again manually. 

Not critical at all but I also noticed that some songs which used to be in these playlist disappeared. 
Don't know if it is related or if it is linked to the cache issue that already got reported. 

FYI, I only have around 10 Playlist and most of them have between 20 to 40 songs.
If you need more info, feel free to let me know! 

Merry Christmas in advance :)

**Comment by Rawk3rs** [comment]
EDIT: The missing are probably linked to the cache issue as they are no longer showing in the app so by saving the playlist, the "missing" songs get removed from the playlist I guess

**Comment by Alaanor** [comment]
This is a valid issue. I could reproduce it. I will have to fix it :) This is due to the last update.
