### ISSUE TITLE
Download Error: Couldn't Extract Beatmap. [undefined]: undefined

### ISSUE THREAD

**Issue by OtisFromTheBarn** [Alaanor/beatlist#83]
![image](https://user-images.githubusercontent.com/76670690/103184022-e122c500-4883-11eb-9882-6f900e98de8e.png)

Not sure if the image will show, but I have not seen this error message anywhere. I can't seem to download maps from this app, as I get this error each time. I have the plugins installed, the options to one-click download setup, and everything else seems good to go

**Comment by Alaanor** [comment]
I only seen this case when beatsaver was down. Are you sure you're on the latest version (1.2.3, see home page). Could have a better message than this.

**Comment by OtisFromTheBarn** [comment]
Looks like bringing it to 1.2.3 was the trick, didn't realize that came out since I've had this issue for a few weeks. Just decided to look into it now, but it's good to go now!

Thank you!
